---
    - name: "Install Apache2 Webserver"
      become: true
      apt:
        name: apache2
        state: present
        update_cache: yes   
        force: yes

    - name: "Remove current filesystem"
      become: true
      file:
        path: "/var/www/html/hello-world"
        state: absent
        force: yes
    
    - name: "Recreate target filesystem"
      become: true
      file:
        path: "/var/www/html/hello-world"
        state: directory
        owner: root
        group: root
        mode: 0755
    
    - name: "Copy files"
      become: true
      copy:
        src: "/home/kevin/git/hello-world/publish/hello-world"
        dest: "/var/www/html"
        owner: root
        group: root
        mode: 0755
    
    - name: "Restart Apache2 Webserver"
      become: true
      service:
        name: apache2
        state: restarted

    - name: "Deployment Complete"
      debug: msg="Finished"